spawn:
  #-369, 69, 391, 180, 0
  x: -369.5
  y: 69.5
  z: 391.5
  yaw: -180f
  pitch: 0f
  world: world
messages:
  deny: "&4Vous devez être un joueur pour executer cette commande ! "
  setspawn: "&2Le nouveau spawn a bien été défini !"